export default {
    somethingWentWrong: 'Something went wrong!',
    dateValidation: "must be a valid date in the format DD-MM-YYYY",
    passwordNotMatch: "Passwords do not match",
    passwordValidation: "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
    passwordMinValidation: "Password must be at least 8 characters long",
    passwordRequired: "Password is required",
    invalidEmail: "Invalid email",
    EmailRequired: "email is required",
    userExists: "email is already registered",
    userRegSuccess: "user registration completed successfully",
    userRegFailed: "failed to register new user, please try again later.",
    userNotFound: "email not found",
    loginSuccess: "logged in successfully",
    userInactive: "user is not active",
    passwordIncorrect: "incorrect password",
    projectShortMin: 'Project short name must be at least 2 characters',
    projectShortMax: 'Project short name must be at most 4 characters',
    createProjectFailed: "Failed to create project",
    createProjectSuccess: "Project created successfully",
}